using System;
using System.Data;
using System.Windows;
using System.Windows.Controls;

namespace mm34wpf
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void gridPreview_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = sender as DataGrid;
            var table = (grid.ItemsSource as DataView).Table;
            var colIndex = -1;
            foreach (var column in grid.Columns)
            {
                colIndex++;
                column.Header = table.Columns[colIndex].Caption;
            }
        }
    }
}